version: "3"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
  web:
    build: ./cir_app
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./cir_app:/code
      - ./data/tmp:/data/tmp
    ports:
      - "8000:8000"
    depends_on:
      - db